"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['app.py']
DATA_FILES = ['arial1.ttf','graphics/3 hearts.jpeg','graphics/empty_heart.png','graphics/ground.jpeg','graphics/guard1.png','graphics/full_heart.png','graphics/player.png','graphics/prison.png','graphics/heart.png','graphics/half_heart.png']

OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
